### ISSUE TITLE
Using scope property for tokeninfo

### ISSUE THREAD

**Issue by jans510** [zalando-stups/mocks#16]
I'm using this mock together with stups-spring-oauth2-support https://github.com/zalando-stups/stups-spring-oauth2-support.

On requesting the token info, this mock serves a 'scopes' property (line 210 in server.js) but a 'scope' property is needed (LaxAuthenticationExtractor class line 52 https://github.com/zalando-stups/stups-spring-oauth2-support/blob/master/stups-spring-oauth2-server/src/main/java/org/zalando/stups/oauth2/spring/server/LaxAuthenticationExtractor.java).

I don't know where to fix it best.

**Comment by prayerslayer** [comment]
Yeah, someone using our mocks! :tada:

Will check as soon as I can.

**Comment by prayerslayer** [comment]
Released under `stups/mock-oauth2-provider:0.0.5` and updated `latest` as well. Please shout if run in to further problems.

**Comment by jans510** [comment]
:+1:
