### ISSUE TITLE
TokenInfoResourceServerTokenService doesn't handle expired tokens

### ISSUE THREAD

**Issue by jans510** [zalando-stups/mocks#19]
The tokenInfo endpoint of the mock sends an error message with a status code of 400, if the token doesn't exist or is expired. This error isn't handled by the TokenInfoResourceServerToken.loadAuthentication method (https://github.com/zalando-stups/stups-spring-oauth2-support/blob/master/stups-spring-oauth2-server/src/main/java/org/zalando/stups/oauth2/spring/server/TokenInfoResourceServerTokenServices.java, if(map.contains("error"))) in my case, as Springs DefaultResponseErrorHandler throws an HTTPClientErrorException before (because of the 400er status).

Is this an issue of this mock or is it usual to send a status code 400 from the tokenInfo endpoint for expired tokens?

**Comment by prayerslayer** [comment]
> Is this an issue of this mock or is it usual to send a status code 400 from the tokenInfo endpoint for expired tokens?

Afaik it's not defined in the OAuth2 spec, but our IAM provider yields 400s when given invalid or expired tokens (which you can easily verify yourself).

I will close this because from my perspective this behavior is as expected. Please open an issue in the other project. Thank you!
