### ISSUE TITLE
Image not available on docker

### ISSUE THREAD

**Issue by mdedetrich** [zalando-stups/mocks#29]
The image for the mock Zalando server doesn't appear to be available on Docker anymore

**Comment by prayerslayer** [comment]
True, we moved them to our own docker registry. You can download them from `registry.opensource.zalan.do/stups/mock-[team-service | oauth2-provider | token-service]:0.1`, I will update the docs accordingly.

**Comment by mdedetrich** [comment]
Thanks!

**Comment by prayerslayer** [comment]
Should be up to date now. Thanks for reporting!
